### ISSUE TITLE
Upgrade to phoenix_pubsub to version 2 for phoenix 1.5 and up projects

### ISSUE THREAD

**Issue by iceniveth** [gmtprime/yggdrasil#9]
I think we should upgrade the `pubsub` to support the phoenix 1.5 projects and up.

Currently, this is what's happening after `mix deps.get`:

![image](https://user-images.githubusercontent.com/16744414/103509498-3ec79a80-4e9e-11eb-9544-405a5eee00c8.png)

**Comment by alexdesousa** [comment]
@iceniveth Thanks for your interest in Yggdrasil! Upgrading this library has been in my TODO list for a while now. I'll try to do it soon :smile:

**Comment by alexdesousa** [comment]
@iceniveth Finally found some time to update the dependencies of the project. I've just released Yggdrasil v6.0.0. Due to the libraries I'm using is compatible with OTP >= 23 and preferably Elixir 1.12 :)
